API-token: ""
debug: false
roles-to-sync:
  TwitchFollower:
    conditions:
      - TwitchFollower()
    permissions:
      - group.TwitchFollower
  YouTubeSubscriber:
    conditions:
      - YouTubeSubscriber()
    permissions:
      - group.YouTubeSubscriber
  TwitchSubscriber:
    conditions:
      - TwitchSubscriber()
    permissions:
      - group.TwitchSubscriber
  PatreonSupporterTier1:
    conditions:
      - PatreonMember("Supporter of Things")
    permissions:
      - group.PatreonTier1
  FollowerOfAll:
    conditions:
      - YouTubeSubscriber() and TwitchFollower()
    permissions:
      - group.FollowerOfAll